### ISSUE TITLE
Ask for detailed usage of your outstanding code！！

### ISSUE THREAD

**Issue by SZW-zjbd** [DenglinGo/CONICA#1]
Dear author, hello. I am very interested in the work of your article and would like to reproduce it in the near future. Do you have detailed instructions for using the source code?

**Comment by DenglinGo** [comment]
Hello!
We've released detailed instructions for using our code.
Please note that the code is not currently well-formatted, and there may still be some bugs present. I plan to revisit it to address these issues and ensure its cleanliness later.
Thank you for your interest!
